#!/usr/bin/env python3

import argparse
import logging

from cvmfspubtools.config import read_config
from cvmfspubtools.consume import add_consume_arguments, consume_jobs
from cvmfspubtools.submit import add_submit_arguments, submit_job


def parse_args():
    parser = argparse.ArgumentParser(description='CVMFS publishing job tool.')

    subparsers = parser.add_subparsers(dest='command')
    subparsers.required = True

    add_consume_arguments(subparsers)
    add_submit_arguments(subparsers)

    return parser.parse_args()


def main():
    logging.basicConfig(level=logging.INFO)

    logging.info('CVMFS publishing job tool')

    arguments = parse_args()

    config_file = arguments.config

    config = read_config(config_file)
    rabbitmq_config = config['rabbitmq']

    if arguments.command == 'submit':
        submit_job(rabbitmq_config, arguments)
    elif arguments.command == 'consume':
        consume_jobs(rabbitmq_config, arguments)

if __name__ == '__main__':
    main()
