language: go

go:
  - 1.11.x
  - 1.12.x

env:
  - GO111MODULE=on

notifications:
  email:
    recipients:
      - radu.popescu@cern.ch
    on_success: change
    on_failure: always

script: go test -v ./...
