version: "3"
services:
  pg:
    image: postgres:11
    environment:
      - "POSTGRES_PASSWORD=password"
    volumes:
      - "/opt/cvmfs-publisher-data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
  rmq:
    image: rabbitmq:3-management
    hostname: rabbit00
    environment:
      - "RABBITMQ_ERLANG_COOKIE=secret"
      - "RABBITMQ_NODENAME=rabbit@rabbit00"
    ports:
      - "15672:15672"
      - "5672:5672"