version: "3"
services:
  mariadb:
    image: mariadb:5.5
    environment:
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_DATABASE=devcvmfs"
      - "MYSQL_USER=cvmfs_db"
      - "MYSQL_PASSWORD=password"
    volumes:
      - "/opt/cvmfs-publisher-data:/var/lib/mysql"
    ports:
      - "3306:3306"
  rmq:
    image: rabbitmq:3-management
    hostname: rabbit00
    environment:
      - "RABBITMQ_ERLANG_COOKIE=secret"
      - "RABBITMQ_NODENAME=rabbit@rabbit00"
    ports:
      - "15672:15672"
      - "5672:5672"