# Options common to multiple components (worker, server, etc.)
shared_key = "UNSET" # api key shared by server, worker, submit.
job_wait_timeout = 7200 # max number of seconds to wait for jobs to complete
debug = false # enable debug logging
log_timestamps = false # include timestamps in logging output

# Job server configuration is used by conveyor {submit, consumer, server}
[server]
host = "UNSET"
port = 8080

# Queue configuration is used by conveyor server
[queue]
username = "UNSET"
password = "UNSET"
host = "UNSET"
port = 5672
vhost = "/"

# Job server backend configuration is only used by conveyor server
[db]
type = "UNSET" # postgres | mysql
database = "UNSET"
username = "UNSET"
password = "UNSET"
host = "UNSET"
port = 5432

# Worker configuration
[worker]
# name = defaults to hostname
job_retries = 3
# temp_dir = defaults to "/tmp/conveyor-worker-<WORKER NAME>"
