# Job server configuration is used by cvmfs_job {submit, consumer, server}
[server]
host = "JOB SERVICE HOST NAME"
port = 8080
keydir = "/etc/cvmfs/keys" # Default key dir

# Queue configuration is used by cvmfs_job server
[queue]
username = "QUEUE USER NAME"
password = "QUEUE USER PASSWORD"
host = "QUEUE HOST NAME"
port = 5672
vhost = "/"

# Job server backend configuration is only used by cvmfs_job server
[db]
type = "mysql"
database = "devcvmfs"
username = "DB_USERNAME"
password = "DB_PASSWORD"
host = "DB_HOST NAME"
post = 3306