---
- name: Set up the job queue host
  roles:
    - job_queue
  hosts: cvmfs_publisher_hosts
  remote_user: root
  become: yes
  tags: rabbitmq
  tasks:
    - name: Install PostgreSQL
      yum: name="postgresql-server,postgresql-contrib,python-psycopg2"

    - name: Ensure DBs are created
      postgresql_db: name={{item}}
      become_user: postgres
      with_items:
          - DevCVMFS
          - CVMFS
          - TestCVMFS

    - name: Add user to PostgreSQL
      become_user: postgres
      postgresql_user: db={{item}} name={{ postgresql_user }} password={{ postgresql_pass }} priv=ALL
      with_items:
          - DevCVMFS
          - CVMFS
          - TestCVMFS

    - name: Add remote access to PostgreSQL configuration
      script: configure_postgresql.sh

    - name: Start PostgresSQL service
      systemd: name=postgresql enabled=yes state=restarted

    - name: Install RabbitMQ
      yum: name="rabbitmq-server"

    - name: Start Firewalld
      service: name=firewalld enabled=yes state=started

    - name: Open firewall port 5432 for the PostgreSQL
      firewalld: port=5432/tcp permanent=true state=enabled

    - name: Open firewall port 5672 for TCP
      firewalld: port=5672/tcp permanent=true state=enabled

    - name: Open firewall port 15672 for the management console
      firewalld: port=15672/tcp permanent=true state=enabled

    - name: Reload Firewalld
      service: name=firewalld enabled=yes state=reloaded

    - name: Start RabbitMQ server
      systemd: name=rabbitmq-server enabled=yes state=started

    - name: Configure RabbitMQ
      script: configure_rabbitmq.sh {{ admin_user }} {{ admin_pass }} {{ worker_user }} {{ worker_pass }}

    - name: Increase max number of open file descriptors for the rabbitmq user
      copy: src="20-nofile.conf" dest="/etc/security/limits.d/"

    - name: Create directory /etc/systemd/system/rabbitmq-server.service.d/
      file: path=/etc/systemd/system/rabbitmq-server.service.d state=directory

    - name: Increase max number of open file descriptors (RabbitMQ setting)
      copy: src="rabbitmq-limits.conf" dest="/etc/systemd/system/rabbitmq-server.service.d/limits.conf"

    - name: Restart RabbitMQ server
      systemd: name=rabbitmq-server enabled=yes daemon_reload=yes state=restarted
