---
- name: Set up the job queue host
  roles:
    - job_queue
  hosts: cvmfs_publisher_hosts
  remote_user: root
  become: yes
  tags: rabbitmq
  tasks:
    #- name: Install Erlang from the RabbitMQ repository
    #  yum: name="https://bintray.com/rabbitmq/rpm/download_file?file_path=erlang%2F21%2Fel%2F7%2Fx86_64%2Ferlang-21.1.1-1.el7.centos.x86_64.rpm"

    - name: Install RabbitMQ
    #  yum: name="https://dl.bintray.com/rabbitmq/all/rabbitmq-server/3.7.8/rabbitmq-server-3.7.8-1.el7.noarch.rpm"
      yum: name="rabbitmq-server"

    - name: Start Firewalld
      service: name=firewalld enabled=yes state=started
    - name: Open firewall port 5672 for TCP
      firewalld: port=5672/tcp permanent=true state=enabled
    - name: Open firewall port 15672 for the management console
      firewalld: port=15672/tcp permanent=true state=enabled
    - name: Reload Firewalld
      service: name=firewalld enabled=yes state=reloaded

    - name: Start RabbitMQ server
      systemd: name=rabbitmq-server enabled=yes state=started

    - name: Configure RabbitMQ
      script: configure_rabbitmq.sh {{ admin_user }} {{ admin_pass }} {{ worker_user }} {{ worker_pass }}

    #- name: Configure RabbitMQ - send configuration file
    #  copy: src="rabbitmq.conf" dest="/etc/rabbitmq/rabbitmq.conf"

    - name: Increase max number of open file descriptors for the rabbitmq user
      copy: src="20-nofile.conf" dest="/etc/security/limits.d/"

    - name: Create directory /etc/systemd/system/rabbitmq-server.service.d/
      file: path=/etc/systemd/system/rabbitmq-server.service.d state=directory

    - name: Increase max number of open file descriptors (RabbitMQ setting)
      copy: src="rabbitmq-limits.conf" dest="/etc/systemd/system/rabbitmq-server.service.d/limits.conf"

    - name: Restart RabbitMQ server
      systemd: name=rabbitmq-server enabled=yes daemon_reload=yes state=restarted
