---
- name: Set up the job queue host
  roles:
    - job_queue
  hosts: cvmfs_notify_hosts
  remote_user: root
  become: yes
  tags: rabbitmq
  tasks:
    - name: Install prerequisites
      yum: name="wget,unzip"

    - name: Install Erlang from the RabbitMQ repository
      yum: name="https://bintray.com/rabbitmq/rpm/download_file?file_path=erlang%2F21%2Fel%2F7%2Fx86_64%2Ferlang-21.0.9-1.el7.centos.x86_64.rpm"

    - name: Install RabbitMQ
      yum: name="https://dl.bintray.com/rabbitmq/all/rabbitmq-server/3.7.8/rabbitmq-server-3.7.8-1.el7.noarch.rpm"

    - name: Start Firewalld
      service: name=firewalld enabled=yes state=started
    - name: Open firewall port tcp:80 for Websockets
      firewalld: service=http permanent=true state=enabled
    - name: Open firewall ports 5671 and 5672
      firewalld: port=5671-5672/tcp permanent=true state=enabled
    - name: Open firewall port 4930
      firewalld: port=4930/tcp permanent=true state=enabled
    - name: Open firewall ports 15672 for the management console
      firewalld: port=15672/tcp permanent=true state=enabled
    - name: Reload Firewalld
      service: name=firewalld enabled=yes state=reloaded

    - name: Start RabbitMQ server
      systemd: name=rabbitmq-server enabled=yes state=started

    - name: Create plugin directory for RabbitMQ
      file: path=/usr/lib/rabbitmq/plugins state=directory
    - name: Install the Last-Value-Cache plugin
      unarchive:
        src: https://dl.bintray.com/rabbitmq/community-plugins/3.7.x/rabbitmq_lvc_exchange/rabbitmq_lvc_exchange-20171201-3.7.x.zip
        dest: /usr/lib/rabbitmq/plugins
        remote_src: yes

    - name: Configure RabbitMQ - vhost, users, enable plugins
      script: configure_rabbitmq.sh {{ admin_user }} {{ admin_pass }} {{ publisher_user }} {{ publisher_pass }} {{ subscriber_user }} {{ subscriber_pass }}

    - name: Configure RabbitMQ - send configuration file
      copy: src="rabbitmq.conf" dest="/etc/rabbitmq/rabbitmq.conf"

    - name: Increase max number of open file descriptors for the rabbitmq user
      copy: src="20-nofile.conf" dest="/etc/security/limits.d/"

    - name: Create directory /etc/systemd/system/rabbitmq-server.service.d/
      file: path=/etc/systemd/system/rabbitmq-server.service.d state=directory

    - name: Increase max number of open file descriptors (RabbitMQ setting)
      copy: src="rabbitmq-limits.conf" dest="/etc/systemd/system/rabbitmq-server.service.d/limits.conf"

    - name: Restart RabbitMQ server
      systemd: name=rabbitmq-server enabled=yes daemon_reload=yes state=restarted

